id: A45655A96
base_file: fA600.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - nl
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-05-30 22:52:41.110785
  last_modified_at: 2022-05-30 22:52:41.110792
