id: A45655A96
base_file: f0C9F.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 22:52:41.102312
  last_modified_at: 2022-05-30 22:52:41.102327
